name: Run Jest Tests on Pull Requests

# Triggers the workflow on pull requests targeting the main branch.
on:
  pull_request:
    branches: [main]

jobs:
  npm_run_test:
    name: Run Jest tests
    # Specifies the runner environment.
    runs-on: ubuntu-latest

    # Defines the sequence of steps to be executed.
    steps:
      # Checks out the repository code to the runner.
      - uses: actions/checkout@v4

      # Sets up Node.js environment, and enables caching of npm dependencies to
      # speed up future runs.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Installs project dependencies using 'npm ci' for a clean install based
      # on package-lock.json.
      - name: Install dependencies
        run: npm ci

      # Runs Jest tests as defined in the project's package.json
      - name: Run Jest tests
        run: npm run test
